/**
 * Static lookup maps for normalizing raw wiki field values.
 * All maps key on lowercase trimmed input.
 */

/** Strip wiki markup artifacts, HTML tags, and excessive whitespace. */
export function cleanText(raw: string): string {
  return raw
    .replace(/<[^>]+>/g, '')       // strip HTML tags
    .replace(/\[\[([^\]|]+)\|?([^\]]*)\]\]/g, (_, link, display) => display || link) // [[link|display]]
    .replace(/\{\{[^}]+\}\}/g, '') // strip wiki templates
    .replace(/\s+/g, ' ')
    .trim();
}

export const BODY_MATERIAL_MAP: Record<string, string> = {
  basswood: 'Basswood',
  'american basswood': 'Basswood',
  alder: 'Alder',
  ash: 'Ash',
  'swamp ash': 'Swamp Ash',
  'light ash': 'Ash',
  'solid ash': 'Ash',
  'selected solid ash': 'Ash',
  mahogany: 'Mahogany',
  'african mahogany': 'African Mahogany',
  'honduran mahogany': 'Mahogany',
  'honduras mahogany': 'Mahogany',
  'solid mahogany': 'Mahogany',
  'laminated mahogany': 'Mahogany',
  'soft maple': 'Soft Maple',
  'light american maple': 'Maple',
  poplar: 'Poplar',
  maple: 'Maple',
  'flamed maple': 'Flamed Maple',
  'quilted maple': 'Quilted Maple',
  'spalted maple': 'Spalted Maple',
  'soft flame maple': 'Flamed Maple',
  walnut: 'Walnut',
  nyatoh: 'Nyatoh',
  meranti: 'Meranti',
  agathis: 'Agathis',
  okoume: 'Okoume',
  nato: 'Nato',
  bubinga: 'Bubinga',
  korina: 'Korina',
  limba: 'Limba',
  sapele: 'Sapele',
  birch: 'Birch',
  linden: 'Linden',
  teak: 'Teak',
  saman: 'Saman',
  jelutong: 'Jelutong',
  camphor: 'Camphor',
  'monkey pod': 'Monkey Pod',
  luthite: 'Luthite',
  resoncast: 'Resoncast',
  acrylic: 'Acrylic',
  plywood: 'Plywood',
  'plywood maple': 'Plywood',
  'hawaiian koa': 'Koa',
  koa: 'Koa',
};

export const FRETBOARD_MATERIAL_MAP: Record<string, string> = {
  rosewood: 'Rosewood',
  'indian rosewood': 'Rosewood',
  'sonokeling rosewood': 'Rosewood',
  'selected rosewood': 'Rosewood',
  'dark rosewood': 'Rosewood',
  'select dark rosewood': 'Rosewood',
  'selected dark rosewood': 'Rosewood',
  'long-grain rosewood': 'Rosewood',
  'marbled rosewood': 'Rosewood',
  's-tech rosewood': 'Rosewood',
  'ebonized rosewood': 'Rosewood',
  'ebonized': 'Rosewood',
  'ebonised rosewood': 'Rosewood',
  'ebonized (rosewood)': 'Rosewood',
  ebony: 'Ebony',
  'black ebony': 'Ebony',
  'selected ebony': 'Ebony',
  'pale moon ebony': 'Ebony',
  'madagascar ebony': 'Ebony',
  'white ebony': 'White Ebony',
  'selected white ebony': 'White Ebony',
  'kalimantan ebony': 'Ebony',
  'selected kalimantan ebony': 'Ebony',
  'selected stripe ebony': 'Ebony',
  'macassar ebony': 'Macassar Ebony',
  'selected macassar ebony': 'Macassar Ebony',
  maple: 'Maple',
  'bound maple': 'Maple',
  'rock maple': 'Maple',
  'hard maple': 'Maple',
  'selected maple': 'Maple',
  'selected figured maple': 'Maple',
  'spalted maple': 'Spalted Maple',
  'spalted maple (stabilized)': 'Spalted Maple',
  'curly maple': 'Maple',
  'flame maple': 'Maple',
  'flamed maple': 'Maple',
  'birdseye maple': 'Birdseye Maple',
  'birds eye maple': 'Birdseye Maple',
  'bound birdseye maple': 'Birdseye Maple',
  'roasted maple': 'Roasted Maple',
  's-tech roasted maple': 'Roasted Maple',
  's-tech roasted flamed maple': 'Roasted Maple',
  's-tech roasted birdseye maple': 'Roasted Maple',
  'roasted birdseye maple': 'Roasted Maple',
  'roasted flamed maple': 'Roasted Maple',
  'thermo aged maple': 'Roasted Maple',
  'thermo-aged maple': 'Roasted Maple',
  'one-piece s-tech roasted maple': 'Roasted Maple',
  'one-piece s-tech roasted flamed maple': 'Roasted Maple',
  'one-piece s-tech roasted birdseye maple': 'Roasted Maple',
  'cultured maple': 'Maple',
  jatoba: 'Jatoba',
  'treated new zealand pine': 'Treated New Zealand Pine',
  'treated new zealand pine (tnzp)': 'Treated New Zealand Pine',
  purpleheart: 'Purpleheart',
  amaranth: 'Amaranth',
  walnut: 'Walnut',
  richlite: 'Richlite',
  'bound rosewood': 'Rosewood',
  'pau ferro': 'Pau Ferro',
  'thermo aged pau ferro': 'Pau Ferro',
  'thermo-aged pau ferro': 'Pau Ferro',
  ovangkol: 'Ovangkol',
  'thermo-aged ovangkol': 'Ovangkol',
  'panga panga': 'Panga Panga',
  laurel: 'Laurel',
  'nandu wood': 'Nandu Wood',
  katalox: 'Katalox',
  cocobolo: 'Cocobolo',
  wenge: 'Wenge',
  'selected wenge': 'Wenge',
  'bolivian rosewood': 'Rosewood',
  'brazilian rosewood': 'Rosewood',
  'honduran rosewood': 'Rosewood',
  'madagascar rosewood': 'Rosewood',
  'hardwood': 'Hardwood',
  'hardwood grained': 'Hardwood',
  merbau: 'Merbau',
  granadillo: 'Granadillo',
};

export const NECK_MATERIAL_MAP: Record<string, string> = {
  maple: 'Maple',
  'hard maple': 'Maple',
  'hard rock maple': 'Maple',
  'quartersawn maple': 'Maple',
  'quartersawn hard rock maple': 'Maple',
  'quartersawn canadian maple': 'Maple',
  'quartersawn canadian hard rock maple': 'Maple',
  'eastern white maple': 'Maple',
  'flamed maple': 'Maple',
  'birdseye maple': 'Birdseye Maple',
  'roasted maple': 'Roasted Maple',
  'one-piece roasted maple': 'Roasted Maple',
  'one-piece s-tech roasted maple': 'Roasted Maple',
  'one-piece s-tech roasted flamed maple': 'Roasted Maple',
  'one-piece s-tech roasted birdseye maple': 'Roasted Maple',
  'one-piece thermo-aged mahogany': 'Mahogany',
  'one-piece thermo-aged nyatoh': 'Nyatoh',
  'one-piece thermo-aged african mahogany': 'African Mahogany',
  'thermo-aged african mahogany': 'African Mahogany',
  '5-piece thermo-aged african mahogany': 'African Mahogany',
  'roasted flamed maple': 'Roasted Maple',
  '5pc roasted flamed maple': 'Roasted Maple',
  '5-piece roasted maple': 'Roasted Maple',
  '5-piece roasted maple/ bubinga': 'Roasted Maple',
  mahogany: 'Mahogany',
  'african mahogany': 'African Mahogany',
  'honduran mahogany': 'Mahogany',
  'honduras mahogany': 'Mahogany',
  walnut: 'Walnut',
  bubinga: 'Bubinga',
  wenge: 'Wenge',
  purpleheart: 'Purpleheart',
  'purple heart': 'Purpleheart',
  nyatoh: 'Nyatoh',
  okoume: 'Okoume',
  meranti: 'Meranti',
  nato: 'Nato',
  natoh: 'Nato',
  birch: 'Birch',
  rosewood: 'Rosewood',
  sapele: 'Sapele',
  korina: 'Korina',
  jatoba: 'Jatoba',
  'panga panga': 'Panga Panga',
  granadillo: 'Granadillo',
  'pau ferro': 'Pau Ferro',
  amaranth: 'Amaranth',
  'rock maple': 'Maple',
};

export const HARDWARE_COLOR_MAP: Record<string, string> = {
  chrome: 'Chrome',
  'cosmo black': 'Cosmo Black',
  black: 'Black',
  gold: 'Gold',
  nickel: 'Nickel',
  'black nickel': 'Black Nickel',
  'brushed nickel': 'Brushed Nickel',
};

export const BRIDGE_TYPE_MAP: Record<string, string> = {
  edge: 'Edge',
  'edge zero': 'Edge Zero',
  'edge zero ii': 'Edge Zero II',
  'edge-zero ii': 'Edge Zero II',
  'edge iii': 'Edge III',
  'edge pro': 'Edge Pro',
  'edge pro ii': 'Edge Pro II',
  'lo-pro edge': 'Lo-Pro Edge',
  'lo pro edge': 'Lo-Pro Edge',
  'lo-trs ii': 'Lo-TRS II',
  'lo trs ii': 'Lo-TRS II',
  'gibraltar standard ii': 'Gibraltar Standard II',
  gibraltar: 'Gibraltar',
  fixed: 'Fixed',
  'tight-end r': 'Tight-End R',
  'tight end r': 'Tight-End R',
  'tight-end': 'Tight-End',
  'tight end': 'Tight-End',
  'fat-6': 'FAT-6',
  'fat 6': 'FAT-6',
  't1502': 'T1502',
  'mono-rail': 'Mono-rail',
};

export const COUNTRY_MAP: Record<string, string> = {
  japan: 'Japan',
  'made in japan': 'Japan',
  'crafted in japan': 'Japan',
  korea: 'South Korea',
  'south korea': 'South Korea',
  'republic of korea': 'South Korea',
  indonesia: 'Indonesia',
  'made in indonesia': 'Indonesia',
  china: 'China',
  'made in china': 'China',
  prc: 'China',
  usa: 'USA',
  'united states': 'USA',
  taiwan: 'Taiwan',
  mexico: 'Mexico',
  'czech republic': 'Czech Republic',
  germany: 'Germany',
  'united kingdom': 'UK',
  uk: 'UK',
};

/**
 * Shared regex for splitting on year-range boundaries
 * (e.g. "2016–2018: mahogany2019: nyatoh").
 */
export const yearSplitPattern = /(?=[""]?\d{4}[""]?\s*[-–—]?\s*\d{0,4}[""]?\s*:)/g;

/** Normalize a value against a mapping table. */
export function normalizeWith(value: string, map: Record<string, string>): string {
  const lower = value.toLowerCase().trim();
  return map[lower] ?? value.trim();
}
